### ISSUE TITLE
MapView not Visiable

### ISSUE THREAD

**Issue by Apurba06** [googlemaps/android-samples#106] opened 2018-09-21 06:31 UTC
In my device HUAWEI BND-AL10(Android 8.0.0) no map view visible. I tried all type of examples.

**Comment by lipusal** [comment] 2018-09-25 01:00
You might be missing the Maps API key, as I was. From the README:

> Add your API key to the file debug/values/google_maps_api.xml. It's pulled from there into your app's AndroidManifest.xml file. See the [quick guide to getting an API key](https://developers.google.com/maps/documentation/android-api/signup).

Once I configured the API key and added it to the application, the map displayed properly.

This may be a duplicate of #99

**Closed** 2019-08-30 18:04 UTC
