### ISSUE TITLE
MapWithMarker: Unnable to build project.

### ISSUE THREAD

**Issue by breakyourfists** [googlemaps/android-samples#128] opened 2019-09-29 14:57 UTC
#### Environment details

Project: MapWithMarker
API level: 27
Oreo Android 8.1

#### Steps to reproduce

1 - Git pull
2 - Android Studio 3.5 > File > New > Import Project > Select MapWithMark project.
3 - Get error while building project.

```python
# example
```

#### Stack trace
ERROR: Failed to resolve: com.android.support:appcompat-v7:24.2.1
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.google.android.gms:play-services:9.8.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.android.support.test.espresso:espresso-core:2.2.2
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app

**Comment by jpoehnelt** [comment] 2019-09-30 18:15
I'll try to take a look at and build this example when I get a chance. 

In the meantime, you might get a quicker response on StackOverflow with [`google-maps-android`](https://stackoverflow.com/questions/tagged/google-maps-android-api-2) tag. If you get a solution, please circle back here and share for others and let me know.

**Comment by chinalwb** [comment] 2019-10-10 07:31
Same issue here.

**Comment by kishorecs** [comment] 2019-11-30 04:03
Please share the build logs from your studio, that will help finding the root cause.

Few things might resolve the issue:

1. Use `'androidx.appcompat:appcompat:1.1.0'` instead of `'com.android.support:appcompat-v7:24.2.1'` 
2. Use `'androidx.test.espresso:espresso-core:3.2.0'` instead of `com.android.support.test.espresso:espresso-core:2.2.2`
3. Studio says 

> Avoid using bundled version of Google play SDK.

It means do not use `com.google.android.gms:play-services:9.8.0`
Use like below:
   
`implementation 'com.google.android.gms:play-services-places:9.8.0'`
`implementation 'com.google.android.gms:play-services-maps:9.8.0'`
`implementation 'com.google.android.gms:play-services-location:9.8.0'`

2. Give your **GOOGLE_MAPS_API_KEY** correctly in `gradle.properties` file

**Comment by wangela** [comment] 2019-12-30 21:20
Fixed with PR #141

**Closed by wangela** 2019-12-30 21:20 UTC
Labels: priority: p3, type: question
